# Generated by Django 5.1.1 on 2024-12-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='produtos/'),
        ),
    ]
