# Generated by Django 5.1.1 on 2024-12-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoentrega',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.pedido'),
        ),
    ]
